<?php

namespace Container3DeUTG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5P3hqjRService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5P3hqjR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5P3hqjR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\UserController::add' => ['privates', '.service_locator.R21nC86.App\\Controller\\Admin\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\HomeController::guests' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guests()', 'getHomeControllerguestsService', true],
            'App\\Controller\\HomeController::guest' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guest()', 'getHomeControllerguestService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\UserController:add' => ['privates', '.service_locator.R21nC86.App\\Controller\\Admin\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\HomeController:guests' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guests()', 'getHomeControllerguestsService', true],
            'App\\Controller\\HomeController:guest' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guest()', 'getHomeControllerguestService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\UserController::add' => '?',
            'App\\Controller\\HomeController::guests' => '?',
            'App\\Controller\\HomeController::guest' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\UserController:add' => '?',
            'App\\Controller\\HomeController:guests' => '?',
            'App\\Controller\\HomeController:guest' => '?',
        ]);
    }
}
