<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZAr8mpT\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZAr8mpT/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZAr8mpT.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZAr8mpT\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerZAr8mpT\App_KernelTestDebugContainer([
    'container.build_hash' => 'ZAr8mpT',
    'container.build_id' => '295c7e76',
    'container.build_time' => 1782122956,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZAr8mpT');
