<?php

namespace ContainerZAr8mpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3trmqvtService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.3trmqvt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3trmqvt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AlbumController::index' => ['privates', '.service_locator.LcuPaks.App\\Controller\\Admin\\AlbumController::index()', 'getAlbumControllerindexService', true],
            'App\\Controller\\Admin\\AlbumController::add' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Admin\\AlbumController::add()', 'getAlbumControlleraddService', true],
            'App\\Controller\\Admin\\AlbumController::update' => ['privates', '.service_locator.YqnP_QC.App\\Controller\\Admin\\AlbumController::update()', 'getAlbumControllerupdateService', true],
            'App\\Controller\\Admin\\AlbumController::delete' => ['privates', '.service_locator.YqnP_QC.App\\Controller\\Admin\\AlbumController::delete()', 'getAlbumControllerdeleteService', true],
            'App\\Controller\\Admin\\MediaController::index' => ['privates', '.service_locator.yJblLem.App\\Controller\\Admin\\MediaController::index()', 'getMediaControllerindexService', true],
            'App\\Controller\\Admin\\MediaController::add' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Admin\\MediaController::add()', 'getMediaControlleraddService', true],
            'App\\Controller\\Admin\\MediaController::delete' => ['privates', '.service_locator.Jsoy8s9.App\\Controller\\Admin\\MediaController::delete()', 'getMediaControllerdeleteService', true],
            'App\\Controller\\Admin\\UserController::index' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController::add' => ['privates', '.service_locator.otatEb2.App\\Controller\\Admin\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\Admin\\UserController::delete' => ['privates', '.service_locator.DngcF_t.App\\Controller\\Admin\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\Admin\\UserController::switchAccess' => ['privates', '.service_locator.DngcF_t.App\\Controller\\Admin\\UserController::switchAccess()', 'getUserControllerswitchAccessService', true],
            'App\\Controller\\HomeController::guests' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guests()', 'getHomeControllerguestsService', true],
            'App\\Controller\\HomeController::guest' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guest()', 'getHomeControllerguestService', true],
            'App\\Controller\\HomeController::portfolio' => ['privates', '.service_locator.46fQtN..App\\Controller\\HomeController::portfolio()', 'getHomeControllerportfolioService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AlbumController:index' => ['privates', '.service_locator.LcuPaks.App\\Controller\\Admin\\AlbumController::index()', 'getAlbumControllerindexService', true],
            'App\\Controller\\Admin\\AlbumController:add' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Admin\\AlbumController::add()', 'getAlbumControlleraddService', true],
            'App\\Controller\\Admin\\AlbumController:update' => ['privates', '.service_locator.YqnP_QC.App\\Controller\\Admin\\AlbumController::update()', 'getAlbumControllerupdateService', true],
            'App\\Controller\\Admin\\AlbumController:delete' => ['privates', '.service_locator.YqnP_QC.App\\Controller\\Admin\\AlbumController::delete()', 'getAlbumControllerdeleteService', true],
            'App\\Controller\\Admin\\MediaController:index' => ['privates', '.service_locator.yJblLem.App\\Controller\\Admin\\MediaController::index()', 'getMediaControllerindexService', true],
            'App\\Controller\\Admin\\MediaController:add' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Admin\\MediaController::add()', 'getMediaControlleraddService', true],
            'App\\Controller\\Admin\\MediaController:delete' => ['privates', '.service_locator.Jsoy8s9.App\\Controller\\Admin\\MediaController::delete()', 'getMediaControllerdeleteService', true],
            'App\\Controller\\Admin\\UserController:index' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController:add' => ['privates', '.service_locator.otatEb2.App\\Controller\\Admin\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\Admin\\UserController:delete' => ['privates', '.service_locator.DngcF_t.App\\Controller\\Admin\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\Admin\\UserController:switchAccess' => ['privates', '.service_locator.DngcF_t.App\\Controller\\Admin\\UserController::switchAccess()', 'getUserControllerswitchAccessService', true],
            'App\\Controller\\HomeController:guests' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guests()', 'getHomeControllerguestsService', true],
            'App\\Controller\\HomeController:guest' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\HomeController::guest()', 'getHomeControllerguestService', true],
            'App\\Controller\\HomeController:portfolio' => ['privates', '.service_locator.46fQtN..App\\Controller\\HomeController::portfolio()', 'getHomeControllerportfolioService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\AlbumController::index' => '?',
            'App\\Controller\\Admin\\AlbumController::add' => '?',
            'App\\Controller\\Admin\\AlbumController::update' => '?',
            'App\\Controller\\Admin\\AlbumController::delete' => '?',
            'App\\Controller\\Admin\\MediaController::index' => '?',
            'App\\Controller\\Admin\\MediaController::add' => '?',
            'App\\Controller\\Admin\\MediaController::delete' => '?',
            'App\\Controller\\Admin\\UserController::index' => '?',
            'App\\Controller\\Admin\\UserController::add' => '?',
            'App\\Controller\\Admin\\UserController::delete' => '?',
            'App\\Controller\\Admin\\UserController::switchAccess' => '?',
            'App\\Controller\\HomeController::guests' => '?',
            'App\\Controller\\HomeController::guest' => '?',
            'App\\Controller\\HomeController::portfolio' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\AlbumController:index' => '?',
            'App\\Controller\\Admin\\AlbumController:add' => '?',
            'App\\Controller\\Admin\\AlbumController:update' => '?',
            'App\\Controller\\Admin\\AlbumController:delete' => '?',
            'App\\Controller\\Admin\\MediaController:index' => '?',
            'App\\Controller\\Admin\\MediaController:add' => '?',
            'App\\Controller\\Admin\\MediaController:delete' => '?',
            'App\\Controller\\Admin\\UserController:index' => '?',
            'App\\Controller\\Admin\\UserController:add' => '?',
            'App\\Controller\\Admin\\UserController:delete' => '?',
            'App\\Controller\\Admin\\UserController:switchAccess' => '?',
            'App\\Controller\\HomeController:guests' => '?',
            'App\\Controller\\HomeController:guest' => '?',
            'App\\Controller\\HomeController:portfolio' => '?',
        ]);
    }
}
