<?php

namespace ContainerZAr8mpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumControllerindexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.LcuPaks.App\Controller\Admin\AlbumController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LcuPaks.App\\Controller\\Admin\\AlbumController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'albumRepository' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
        ], [
            'albumRepository' => 'App\\Repository\\AlbumRepository',
        ]))->withContext('App\\Controller\\Admin\\AlbumController::index()', $container);
    }
}
