<?php

namespace ContainerZAr8mpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerportfolioService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.46fQtN..App\Controller\HomeController::portfolio()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.46fQtN..App\\Controller\\HomeController::portfolio()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'albumRepository' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'mediaRepository' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
        ], [
            'albumRepository' => 'App\\Repository\\AlbumRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'mediaRepository' => 'App\\Repository\\MediaRepository',
        ]))->withContext('App\\Controller\\HomeController::portfolio()', $container);
    }
}
