<?php

namespace ContainerZAr8mpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Listener_ResetMemoryUsageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.listener.reset_memory_usage' shared service.
     *
     * @return \Symfony\Component\Messenger\EventListener\ResetMemoryUsageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'messenger'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'ResetMemoryUsageListener.php';

        return $container->privates['messenger.listener.reset_memory_usage'] = new \Symfony\Component\Messenger\EventListener\ResetMemoryUsageListener();
    }
}
