<?php

namespace ContainerZAr8mpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerswitchAccessService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.DngcF_t.App\Controller\Admin\UserController::switchAccess()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DngcF_t.App\\Controller\\Admin\\UserController::switchAccess()'] = ($container->privates['.service_locator.DngcF_t'] ?? $container->load('get_ServiceLocator_DngcFTService'))->withContext('App\\Controller\\Admin\\UserController::switchAccess()', $container);
    }
}
